name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Grant execute permission for Gradle wrapper (if on Unix)
      if: runner.os != 'Windows'
      run: chmod +x gradlew
      
    - name: Build the project
      run: ./gradlew clean build
      shell: bash
    
    - name: Run tests and generate JaCoCo report
      run: ./gradlew test jacocoTestReport
      shell: bash
    
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: lwjgl3/build/reports/jacoco/test/html/jacoco

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: lwjgl3/build/reports/checkstyle/main.xml
